# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

  
os:
  - linux
  - osx

r:
  - release
  - devel
  
jobs:
  exclude:
    - r: devel
      os: osx

# R for codecov: see documentation at https://github.com/codecov/example-r

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

